# Generated by Django 3.2.9 on 2021-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='PhotoFileName',
            field=models.CharField(default='post.jpg', max_length=100),
        ),
    ]
