# Generated by Django 3.2.9 on 2021-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211206_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PhotoFileName',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
