# Generated by Django 3.2.9 on 2021-12-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_photofilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='PhotoFileName',
            new_name='image',
        ),
    ]
