# Generated by Django 3.2.9 on 2021-12-07 04:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_public_post_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auth',
            field=models.TextField(default=django.contrib.auth.models.User),
        ),
    ]
