# Generated by Django 3.2.9 on 2021-12-07 04:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
