# Generated by Django 3.2.9 on 2021-12-07 05:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auth',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=200, null=True),
        ),
    ]
