# Generated by Django 3.2.9 on 2021-12-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_followers'),
        ('posts', '0019_remove_post_author1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
