# Generated by Django 3.2.9 on 2021-12-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_author1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
