# Generated by Django 3.2.9 on 2021-12-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
